### ISSUE TITLE
 Without stealing car this error constantly appears in the F8

### ISSUE THREAD

**Issue by SATTAGAMES** [KlibrDM/esx_carthief#9] opened 2019-05-01 22:49 UTC
http://prntscr.com/nja3j3

**Comment by KlibrDM** [comment] 2019-05-02 07:44
The most important part of the error can't be seen in the screenshot. Try copying it from CitizenFX.log

**Comment by SATTAGAMES** [comment] 2019-05-04 22:17
[    650297] [FT_LIBS] DEBUG MODE DISABLEError running system event handling function for resource esx_carthief: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: @esx_carthief/client/main.lua:34: attempt to call a nil value (global 'CreateBlip')
[    650297] stack traceback:
[    650297] 	@esx_carthief/client/main.lua:34: in upvalue 'handler'
[    650297] 	citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>
[    650297] stack traceback:
[    650297] 	[C]: in function 'error'
[    650297] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[    650297] 	citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>
[    650344] nui://es_ui/ui.html:37, Uncaught TypeError: Cannot set property 'innerHTML' of null

**Comment by KlibrDM** [comment] 2019-05-05 09:09
Duplicate of #7. Try to answer the questions I asked there otherwise I can't really help.

**Closed as completed by KlibrDM** 2019-05-05 09:09 UTC
Labels: duplicate

**Comment by SATTAGAMES** [comment] 2019-05-05 21:50
Plus this I got from CitizenFX log
